### ISSUE TITLE
Median duration

### ISSUE THREAD

**Issue by freeman42x** [bucardo/pgsi#3]
Median duration shows as 0 ms for odd and large total count values.

**Comment by turnstep** [comment]
Got a short test case or example? I can't duplicate with some quick fudging of durations.

**Comment by freeman42x** [comment]
It is working fine, I made the wrong assumption that all the timings in the log file were strictly greater than 0. It seems that the minimum duration resolution was 1 ms and when the median was computed to be 0, around half or more timings were equal to 0. I thought it had something to do with computing the median value for even number of timings.

I made some modifications to median computation to account for even number of timings:

```
File: pgsi.pl
@@ -668,11 +668,17 @@ for my $hsh (values %canonical_q) {
         for my $duration ( @{$hsh->{durations}} ) {
             $sum += ($duration - $mean)**2;
         }
         $hsh->{deviation} = sqrt($sum / ($hsh->{count} - 1));
         my @sorted = sort { $a <=> $b } @{$hsh->{durations}};
-        $hsh->{median} = $sorted[int($#sorted / 2)];
+       
+       if (($#sorted + 1) % 2 != 0) {
+           $hsh->{median} = $sorted[int($#sorted / 2)];
+       }
+       else {
+           $hsh->{median} = ($sorted[int($#sorted / 2)] + $sorted[int($#sorted / 2) + 1]) / 2;
+       }
     }
     else {
         $hsh->{deviation} = -1;
         $hsh->{median} = -1;
     }
```

I haven't tested it since I don't have any previous perl experience.

**Comment by turnstep** [comment]
Thanks, patch applied and now part of version 1.7.1:

http://bucardo.org/wiki/Pgsi

## 

Greg Sabino Mullane greg@endpoint.com
End Point Corporation
PGP Key: 0x14964AC8
